### ISSUE TITLE
OnlyOffice AppImage Not Loading

### ISSUE THREAD

**Issue by MichaelTunnell** [ONLYOFFICE/appimage-desktopeditors#13]
I am getting the following error when I try to launch the AppImage:
`symbol lookup error: /usr/lib/libhogweed.so.5: undefined symbol: __gmpn_cnd_sub_n`

OnlyOffice version = 5.4.1
Operating System = Arch Linux

**Comment by ShockwaveNN** [comment]
Duplicate of #3

**Comment by probonopd** [comment]
`libgmp.so.10` would need to be removed from the AppImage.
