### ISSUE TITLE
Where is Appimage for ver 6.0?

### ISSUE THREAD

**Issue by spsf64** [ONLYOFFICE/appimage-desktopeditors#22]
**Do you want to request a *feature* or report a *bug*?**

No Appimage package for version 6.0.0 in releases page

**Which versions of DesktopEditors, and which OS are affected by this issue? Did this work in previous versions of DesktopEditors?**

Ver 6.0.0

**Comment by ShockwaveNN** [comment]
Same question for previous release https://github.com/ONLYOFFICE/appimage-desktopeditors/issues/18

**Comment by romandemidov** [comment]
https://github.com/ONLYOFFICE/appimage-desktopeditors/releases/tag/v6.0.0
