### ISSUE TITLE
Solus: OnlyOffice doesn't work with glib2 version 2.69.x

### ISSUE THREAD

**Issue by algent-al** [ONLYOFFICE/appimage-desktopeditors#25]
Hi!
OnlyOffice not working on Solus with glib2 version 2.69.2
This is the error:
``` 
$ ./DesktopEditors-x86_64.AppImage 
./DesktopEditors: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full
```
With glib2 version 2.68.3 is working fine.

**Comment by JfrAziz** [comment]
I have similiar issue too, Manjaro with glib2 version 2.70.0

**Comment by maop** [comment]
```
$ ./DesktopEditors-x86_64.AppImage 
./DesktopEditors: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_module_open_full
```

Same in Void Linux with glib-2.70.0_2

**Comment by ShockwaveNN** [comment]
This problem fixed in https://github.com/ONLYOFFICE/appimage-desktopeditors/commit/460e49ccb79eccb07c59ae9a7f7f6a141211ac7a

And will be available as soon as we will be ready to release a new version (cannot provide exact ETA)

**Comment by maop** [comment]
I confirm it is fixed in today's release version: 6.4.2.6

Thanks a lot !

**Comment by algent-al** [comment]
I confirm too, that OnlyOffice with the version 6.4.2.6 runs fine on Solus.

**Comment by ShockwaveNN** [comment]
Thank you for your confirmation, in that case I'll close this issue

If you find out any more problems - I think it's better to create new issues

**Comment by ShockwaveNN** [comment]
@memesforlife1 I think it's better to create a new issue with detailed description of your environment

**Comment by memesforlife1** [comment]
> @memesforlife1 I think it's better to create a new issue with detailed description of your environment

Turns out it was just cus I got it from appimage hub and not this GH repo :D, But Dev(s) should really put it on appimageHub or AppimageHub(v2)  for Appimage package managers

**Comment by ShockwaveNN** [comment]
@memesforlife1 We presented at https://appimage.github.io/ this appimage list, don't think we really need to be present on any site that lists appimages

Especially in case that google request `appimage onlyoffice` return correct place to download latest version
