### ISSUE TITLE
Are Snap, Flatpak and AppImage packages abandoned

### ISSUE THREAD

**Issue by N3tFX** [ONLYOFFICE/appimage-desktopeditors#30]
Are Snap, Flatpak and AppImage packages abandoned? The desktop versions of the Editors for deb, rpm etc. are up to version 6.4.2, while the Snap, Flatpak and AppImage packages are stuck to 6.3.1. If anything, these versions that work on most distros, should be the first to be updated, right?

**Comment by ShockwaveNN** [comment]
>  If anything, these versions that work on most distros, should be the first to be updated, right?

Sorry, but this is how our release process works and currently we're not planning to change that

And to be clear - snap and flatpak should be v6.4.2 since last week

And AppImage is one the way, but cannot guarantee any ETA

**Comment by N3tFX** [comment]
I've just checked the ONLYOFFICE web page ([https://www.onlyoffice.com/download-desktop.aspx](url)) and all three of them (Snap, Flatpak and AppImage) are still in 6.3.1 version.

Since this is by design, I am closing this issue.

**Comment by ShockwaveNN** [comment]
@N3tFX Thanks for noticing that we didn't update our main site, we'll fix it

But generally speaking - a better way to check update - check according to repos of product, especially for AppImage - single option that do not updates itself automatically
