### ISSUE TITLE
Linux ARM version?

### ISSUE THREAD

**Issue by poVoq** [ONLYOFFICE/appimage-desktopeditors#32]
Since version 6.4 seems to be able to compile for native ARM platforms (on Mac at least), would it be possible to provide a Appimage for Linux ARM systems?

**Comment by ShockwaveNN** [comment]
Sorry, we still do have not enough resources to make a fully-working and production ready version of our flagship product -  DocumentServer on the arm

So until we resolved that issues, I don't think we start working on DesktopEdtiors on Linux ARM

**Comment by Botspot** [comment]
Now that issues with ARM DocumentServer have been resolved, can progress be made on this?
I would eagerly add it to [the Pi-Apps store](https://github.com/Botspot/pi-apps) - alongside LibreOffice and WPS Office.

**Comment by Rita-Bubnova** [comment]
Duplicate of https://github.com/ONLYOFFICE/DesktopEditors/issues/270.
