### ISSUE TITLE
Complete lockup at document creation or opening

### ISSUE THREAD

**Issue by aknight2015** [ONLYOFFICE/appimage-desktopeditors#38]
Whenever I try to open or create a document it just locks up. It's a completely blank document window. I downloaded the AppImage so I could see what was going on. It keeps throwing up
QXcbConnection: XCB error: 8 (BadMatch), sequence: 2106, resource id: 6291532, major code: 130 (Unknown), minor code: 3
whenever I try to open or create anything.

**Comment by ShockwaveNN** [comment]
Hi, could you specify your system, and maybe it has something to do with Wayland?

Also try to restart your system

**Comment by aknight2015** [comment]
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

I made sure to install the wayland-protocols package for my Debian release via CLI.
I'm running everything using the Debian release within ChromeOS.

**Comment by ShockwaveNN** [comment]
> Debian release within ChromeOS.

Could you explain that this mean? Is this some kind of virtualization inside ChromeOS?

I'm sorry, but we have no ChromeOS device at our disposal so if this is a problem only for ChromeOS I'm not sure how we can reproduce\fix it

**Comment by aknight2015** [comment]
It's a virtualized container running Debian CLI. It does have a window manager as I can run programs that utilize a GUI. I believe it's Gnome.

**Comment by ShockwaveNN** [comment]
I think it's still somehow related to Chrome OS under virtualization layer

If you'll able to reproduce this error on some virtual ChromeOS or on another non-ChromeOS system - we'll definitely take a closer look

But without any devices I don't think we can do anything

**Comment by XDmitryK** [comment]
I'll tested 8.1.0 on a Chrome OS laptop and there are no issues.

**Comment by aknight2015** [comment]
It was 2 years go that I had this issue. I really have no idea what was going on at the time.
