### ISSUE TITLE
symbol lookup error libgnutls in SolusOS

### ISSUE THREAD

**Issue by Juankz** [ONLYOFFICE/appimage-desktopeditors#4]
Trying to use appimage of desktop editors in Solus OS. Does not run.

At first it shows:
`./DesktopEditors: error while loading shared libraries: libkeyutils.so.1: cannot open shared object file: No such file or directory`

Which can be easily solved by installing keyutils. (However isn't it supposed that appimage bundle all neccesary dependencies?). Well never mind, then trying to run it again but throws:

`./DesktopEditors: symbol lookup error: /usr/lib/libgnutls.so.30: undefined symbol: __gmpn_cnd_sub_n`

And I'm stuck in there.

Probably related to #3

**Comment by ShockwaveNN** [comment]
Can confirm on latest Solus Budgie

**Comment by probonopd** [comment]
> However isn't it supposed that appimage bundle all neccesary dependencies?)

No, the AppImage is supposed to bundle those dependencies that cannot reasonably be expected to come in the default installation of the major Linux distributions in a recent enough version. According to https://github.com/AppImage/AppImages/blob/master/excludelist we are currently assuming `libkeyutils.so.1` to be part of each target system (distribution), and apparently this seems to hold true for most indeed.

**Comment by probonopd** [comment]
> undefined symbol: `__gmpn_cnd_sub_n`

Seems to have to do with `libgmp.so.10`?

**Comment by agolybev** [comment]
libkeyutils.so.1 is in [excludelist](https://github.com/AppImage/AppImages/blob/master/excludelist)
libglu1-mesa (libGLU.so.1 dependency) is in [excludedeblist](https://github.com/AppImage/AppImages/blob/master/excludedeblist)
We have to discuss about it with [AppImages](https://github.com/AppImage/AppImages) developers.

**Comment by probonopd** [comment]
> but got another dependency problem

Can you describe the problem please? We assume the libraries listed there to come with the target systems (distributions).

**Comment by agolybev** [comment]
@probonopd, Is exists a way to use local `excludelist` and `excludedeblist` to check solution?

**Comment by probonopd** [comment]
I think you'd need to edit the scripts a bit.

**Comment by agolybev** [comment]
Hi @probonopd, I've made pull requests to fix this issue:
https://github.com/AppImage/AppImages/pull/338
https://github.com/ONLYOFFICE/appimage-desktopeditors/pull/5

**Comment by ShockwaveNN** [comment]
@agolybev Still actual with https://github.com/ONLYOFFICE/appimage-desktopeditors/releases/tag/v5.1.29-2
`./DesktopEditors: symbol lookup error: /usr/lib/libgnutls.so.30: undefined symbol: __gmpn_cnd_sub_n`

**Comment by ShockwaveNN** [comment]
Rechecked latest AppImage with latest image of Solus - everything seems fine
I'm closing this issue
