### ISSUE TITLE
Portable version for Microsoft Windows

### ISSUE THREAD

**Issue by SimoLRepo** [ONLYOFFICE/appimage-desktopeditors#45]
Hi, I need a portable version of ONLYOFFICE for Microsoft Windows. This is due not so much to any use on other PCs but to the fact that no data is left in other folders. Is it possible to create a launcher that allows this? Thank you.

**Comment by ShockwaveNN** [comment]
Please do not create duplicates https://github.com/ONLYOFFICE/DesktopEditors/issues/1125
