### ISSUE TITLE
symbol lookup error: /usr/lib/libtiff.so.6: undefined symbol: jpeg12_write_raw_data, version LIBJPEG_8.0

### ISSUE THREAD

**Issue by jpfss** [ONLYOFFICE/appimage-desktopeditors#53]
### Env
```
lsb_release -a                                                                                                    
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	23.0.2
Codename:	Uranos
```
### Problem
![图片](https://github.com/ONLYOFFICE/appimage-desktopeditors/assets/8890352/99d3f5f1-343a-425a-973e-e8dd85587ebe)

**Comment by yataghan012** [comment]
Same Here also on Manjaro.

**Comment by fwn0** [comment]
Same error in Artix:
artix-pc:[artix]:~$ /run/media/artix/data/Develop/DesktopEditors-x86_64.AppImage 
./DesktopEditors: symbol lookup error: /usr/lib/libtiff.so.6: undefined symbol: jpeg12_write_raw_data, version LIBJPEG_8.0

**Comment by sibradzic** [comment]
All Arch-based distros are affected.

**Comment by yataghan012** [comment]
This appimage now works, (update 31-oct) 

https://www.onlyoffice.com/download-desktop.aspx?from=helpcenter

**Comment by XDmitryK** [comment]
I confirm that Onlyoffice runs correctly on Manjaro OS. The issue will be closed. You can reopen this issue if problems still exist.
