### ISSUE TITLE
Segmentation Fault on nitrux

### ISSUE THREAD

**Issue by ShockwaveNN** [ONLYOFFICE/appimage-desktopeditors#6]
1. `wget https://github.com/ONLYOFFICE/appimage-desktopeditors/releases/download/v5.1.29/DesktopEditors-x86_64.AppImage`
2. `chmod a+x DesktopEditors-x86_64.AppImage`
3. `./DesktopEditors-x86_64.AppImage`
Got
```
desktop-file-validate is missing. Skipping /tmp/.mount_DesktorzG9vX/usr/bin//onlyoffice-desktopeditors.sh.wrapper.
Segmentation fault (core dumped)
```

On [Nitrux](https://nxos.org/) - `nitrux_release_1.0.16-1.iso`

**Comment by ShockwaveNN** [comment]
Same with https://github.com/ONLYOFFICE/appimage-desktopeditors/commit/16bf4d4b1b6172dd711f1ec06e364e8a9e3d57f4

**Comment by probonopd** [comment]
It would be best to get rid of the `onlyoffice-desktopeditors.sh.wrapper` bash script altogether. Users who want desktop integration could use the optional `appimaged` daemon or tools like AppImageLauncher.

**Comment by ShockwaveNN** [comment]
I've tried to recheck this problem on fresh Nitrux setup - but I got troubles with even updating it

I don't think this problem is actual any more
I'll close this issue but if someone still using Nitrux and got this problem - feel free to commend and I'll investigate it in more details
